package com.hb.employeeservice.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(
        description = "EmployeeDTO Models Information"
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class EmployeeDTO {

    @Schema(
            description = "Employee Id - Autogenerated"
    )
    private Long id;

    @Schema(
            description = "First Name"
    )
    private String firstName;

    @Schema(
            description = "Last Name"
    )
    private String lastName;

    @Schema(
            description = "email"
    )
    private String email;

    @Schema(
            description = "Department Code"
    )
    @NotEmpty(message = "Field: departmentCode cannot be empty. ")
    @NotNull
    private String departmentCode;


    @Schema(
            description = "Organization Code"
    )
    private String organizationCode;
}
